title: Claptrap
description:
  Claptrap is a robot based on the LEGO MINDSTORMS EV3, whose purpose is to map a previously unknown room. It has been designed by Nathan Biette, Erwan Culerier and Olivier Roques for the OS fall course 2017 in EURECOM.
theme: jekyll-theme-dinky
